#!/bin/sh

asksetting() {
	prefix="/bin/"
	options=$(printf '%s\n' ${PATH//:/\/* } | grep "instamenu_" | sed '/smartrun/d' | grep -oP "^$prefix\K.*")
    echo ">>h Select App to run
$options" | instamenu -c -l 15 -w -400 -i -h -1 -bw 4 -q "${1:-Search...}"
}

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do
    choice="$(asksetting)"
    unset LOOPSETTING
	if [ "$choice" ]; then
		$choice
		exit
	else 
		echo "Program terminated." && exit
	fi
done
