#!/bin/sh

asksetting() {
    echo ">>h Run a App
instamenu_editor
instamenu_emoji
instamenu_mount
instamenu_network
instamenu_path
instamenu_run
instamenu_systemctl_user" | instamenu -c -l 10 -w -400 -i -h -1 -bw 4 -q "${1:-Search...}"
}

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do
    choice="$(asksetting)"
    unset LOOPSETTING
	if [ "$choice" ]; then
		$choice
	else 
		echo "Program terminated." && exit 1 
	fi
done

