#!/bin/sh

emoji_list=/usr/share/instamenu/emoji-list

emoji_groups=">>h Which Emoji Group?
Smileys & Emotion
People & Body
Animals & Nature
Food & Drink
Travel & Places
Activities
Objects
Symbols
Flags"

emoji_groups_menu=$(printf "%s\n" "$emoji_groups" | \
    instamenu -s -bw 4 -w 600 -c -i -l 20 -q "Selections:")

go_back() {
    /bin/sh /usr/bin/instamenu_emoji
}

case "$emoji_groups_menu" in
    'Smileys & Emotion')
        emoji_group_items=$(sed <"$emoji_list" -n \
            '/group: Smileys \& Emotion/,/group: People \& Body/p' | grep -v '#')
        emoji_group_menu=$(printf "%s\n" ">>h Smileys & Emotion" " ◀ Go Back" \
            "$emoji_group_items" | instamenu -w 600 -c -i -l 20 -q "Select An Emoji")
        if [ "$emoji_group_menu" = " ◀ Go Back" ]; then
            go_back
        else
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 xclip -rmlastnl -selection clipboard
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 while read chosen; do notify-send "'$chosen' copied to clipboard."; done
        fi
    ;;
    'People & Body')
        emoji_group_items=$(sed <"$emoji_list" -n \
            '/group: People \& Body/,/group: Animals \& Nature/p' | grep -v '#')
        emoji_group_menu=$(printf "%s\n" ">>h People & Body" " ◀ Go Back" \
            "$emoji_group_items" | instamenu -w 600 -c -i -l 20 -q "Select An Emoji")
        if [ "$emoji_group_menu" = " ◀ Go Back" ]; then
            go_back
        else
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 xclip -rmlastnl -selection clipboard
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 while read chosen; do notify-send "'$chosen' copied to clipboard."; done
        fi
    ;;
    'Animals & Nature')
        emoji_group_items=$(sed <"$emoji_list" \
            -n '/group: Animals \& Nature/,/group: Food \& Drink/p' | grep -v '#')
        emoji_group_menu=$(printf "%s\n" ">>h Animals & Nature" " ◀ Go Back" \
            "$emoji_group_items" | instamenu -w 600 -c -i -l 20 -q "Select An Emoji")
        if [ "$emoji_group_menu" = " ◀ Go Back" ]; then
            go_back
        else
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 xclip -rmlastnl -selection clipboard
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 while read chosen; do notify-send "'$chosen' copied to clipboard."; done
        fi
    ;;
    'Food & Drink')
        emoji_group_items=$(sed <"$emoji_list" \
            -n '/group: Food \& Drink/,/group: Travel \& Places/p' | grep -v '#')
        emoji_group_menu=$(printf "%s\n" ">>h Food & Drink" " ◀ Go Back" \
            "$emoji_group_items" | instamenu -w 600 -c -i -l 20 -q "Select An Emoji")
        if [ "$emoji_group_menu" = " ◀ Go Back" ]; then
            go_back
        else
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 xclip -rmlastnl -selection clipboard
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 while read chosen; do notify-send "'$chosen' copied to clipboard."; done
        fi
    ;;
    'Travel & Places')
        emoji_group_items=$(sed <"$emoji_list" \
            -n '/group: Travel \& Places/,/group: Activities/p' | grep -v '#')
        emoji_group_menu=$(printf "%s\n" ">>h Travel & Places" " ◀ Go Back" \
            "$emoji_group_items" | instamenu -w 600 -c -i -l 20 -q "Select An Emoji")
        if [ "$emoji_group_menu" = " ◀ Go Back" ]; then
            go_back
        else
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 xclip -rmlastnl -selection clipboard
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 while read chosen; do notify-send "'$chosen' copied to clipboard."; done
        fi
    ;;
    'Activities')
        emoji_group_items=$(sed <"$emoji_list" \
            -n '/group: Activities/,/group: Objects/p' | grep -v '#')
        emoji_group_menu=$(printf "%s\n" ">>h Activities" " ◀ Go Back" \
            "$emoji_group_items" | \instamenu -w 600 -c -i -l 20 -q "Select An Emoji")
        if [ "$emoji_group_menu" = " ◀ Go Back" ]; then
            go_back
        else
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 xclip -rmlastnl -selection clipboard
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 while read chosen; do notify-send "'$chosen' copied to clipboard."; done
        fi
    ;;
    'Objects')
        emoji_group_items=$(sed <"$emoji_list" \
            -n '/group: Objects/,/group: Symbols/p' | grep -v '#')
        emoji_group_menu=$(printf "%s\n" ">>h Objects" " ◀ Go Back" \
            "$emoji_group_items" | instamenu -w 600 -c -i -l 20 -q "Select An Emoji")
        if [ "$emoji_group_menu" = " ◀ Go Back" ]; then
            go_back
        else
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 xclip -rmlastnl -selection clipboard
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 while read chosen; do notify-send "'$chosen' copied to clipboard."; done
        fi
    ;;
    'Symbols')
        emoji_group_items=$(sed <"$emoji_list" \
            -n '/group: Symbols/,/group: Flags/p' | grep -v '#')
        emoji_group_menu=$(printf "%s\n" ">>h Symbols" " ◀ Go Back" \
            "$emoji_group_items" | \instamenu -w 600 -c -i -l 20 -q "Select An Emoji")
        if [ "$emoji_group_menu" = " ◀ Go Back" ]; then
            go_back
        else
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 xclip -rmlastnl -selection clipboard
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 while read chosen; do notify-send "'$chosen' copied to clipboard."; done
        fi
    ;;
    'Flags')
        emoji_group_items=$(sed <"$emoji_list" \
            -n '/group: Flags/,/flag: Zimbabwe/p' | grep -v '#')
        emoji_group_menu=$(printf "%s\n" ">>h Flags" " ◀ Go Back" \
            "$emoji_group_items" | instamenu -w 600 -c -i -l 20 -q "Select An Emoji")
        if [ "$emoji_group_menu" = " ◀ Go Back" ]; then
            go_back
        else
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 xclip -rmlastnl -selection clipboard
            printf "%s" "$emoji_group_menu" | \
                 awk '{print $1}' | \
                 while read chosen; do notify-send "'$chosen' copied to clipboard."; done
        fi
    ;;
esac
