#!/usr/bin/env bash

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/instamenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

IFS=:
if itest -dqr -n "$cache" $PATH; then
	itest -flx $PATH | sort -u | tee "$cache"
else
	cat "$cache"
fi
