#!/usr/bin/env bash
# -*-coding:utf-8 -*-
# Auto updated?
#   Yes
#File :
#   repomenu_path
#Author:
#   The-Repo-Club [wayne6324@gmail.com]
#Github:
#   https://github.com/The-Repo-Club/
#
# Created:
#   Thu 20 January 2022, 04:55:21 PM [GMT]
# Modified:
#   Fri 21 January 2022, 02:29:56 PM [GMT]
#
# Description:
#   <Todo>
#

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/repomenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

IFS=:
if rtest -dqr -n "$cache" $PATH; then
	rtest -flx $PATH | sort -u | tee "$cache"
else
	cat "$cache"
fi
