#!/usr/bin/env bash

# path:       /usr/bin/repomenu_path
# author:     The-Repo-Club [wayne6324@gmail.com]
# github:     https://github.com/The-Repo-Club/repomenu
# date:       2021-01-03 12:34:47.440579

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/repomenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

IFS=:
if itest -dqr -n "$cache" $PATH; then
	itest -flx $PATH | sort -u | tee "$cache"
else
	cat "$cache"
fi
